- name: Copy handler.txt and create tomcat directory
  hosts: all
  become: true
  tasks:
    - name: Copy handler.txt to remote server
      ansible.builtin.copy:
        src: /home/raksha/handler.txt
        dest: /home/raksha/
      notify: Create_Tomcat_directory

  handlers:
    - name: Create_Tomcat_directory
      shell:
        cmd: mkdir -p /home/raksha/tomcat2
